version: "3"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./code:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run start:dev"